name: Deploy to IONOS

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare build directory for SFTP (Include .htaccess) ðŸ› ï¸
        run: |

          mkdir deploy_temp

          shopt -s dotglob

          cp -r build/* build/.* deploy_temp/ 2>/dev/null

          rm -f deploy_temp/. deploy_temp/..

      # Upload the build/ folder to IONOS via SFTP + password
      - name: Deploy to IONOS over SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }} # su482289
          server: ${{ secrets.FTP_SERVER }} # access-...webspace-host.com
          port: ${{ secrets.FTP_PORT }} # 22
          password: ${{ secrets.FTP_PASSWORD }} # your IONOS password
          local_path: "./deploy_temp/*"
          remote_path: "./mhsglobalassociatescom" # where it lives on IONOS
          sftp_only: true # force pure SFTP mode
